RECIPES_CSV_PATH = "Data/Datasets/recipes-1.csv"
IS_RECIPE_CSV = True
PAIRS_CSV_PATH = "Data/Datasets/pairs-1.csv"
IS_PAIRS_CSV = True

# Indexing for recipe lists
UID_INDEX = 0
NAME_INDEX = 1
STEPS_INDEX = 2
INGREDIENTS_INDEX = 3
CATEGORIES_INDEX = 4
NAME_TOKENS_INDEX = 5

# Indexing for recipe pairs lists
BASE_INDEX = 0
TARGET_INDEX = 1
NAME_OVERLAP_INDEX = 2
NAME_SIMILARITY_INDEX = 3

ZERO = 0

BUTTON_COLOR = (148, 124, 92)
TEXT_BOX_COLOR = (245, 245, 220)
SUBMIT_COLOR = (138, 154, 91)
BUTTON_FONT_COLOR = (0, 0, 0)
TEXT_BOX_FONT_COLOR = (0, 0, 0)
TOP_LEFT_CORNER_COORDINATES = (0, 0)

FONT_PATH = "GUI/design_features/font/ShadowsIntoLightTwo-Regular.ttf"

TEXTBOX_BORDER_WIDTH = 45
TEXT_MAX_LENGTH = 40
DEFAULT_TEXT_COLOR = (0, 0, 0)
BUTTON_BORDER_RADIUS = 13
ELLIPSIS_TEXT = "..."
EMPTY_TEXT = ""
LIMIT_REACHED_MESSAGE = "Limit Reached"
NEWLINE_CHARACTER = "\n"
SPACE_CHARACTER = " "

PROGRAM_SCALE = 1.0

CAPTION = 'The Ultimate Recipe Index >:)'
X_DIMENSIONS, Y_DIMENSIONS = int(1000 * PROGRAM_SCALE), int(800 * PROGRAM_SCALE)

MAIN_MENU_IMAGE_FILE_PATH = "GUI/design_features/backgrounds/title.png"
ALGORITHM_IMAGE_FILE_PATH = "GUI/design_features/backgrounds/background_algorithm.png"
SEARCH_IMAGE_FILE_PATH = "GUI/design_features/backgrounds/background_search.png"

TITLE_FONT = int(50 * PROGRAM_SCALE)
CAPTION_FONT = int(25 * PROGRAM_SCALE)
FONT_SIZE = int(20 * PROGRAM_SCALE)
BUTTON_FONT_SIZE = int(25 * PROGRAM_SCALE)
TEXT_BOX_FONT_SIZE = int(18 * PROGRAM_SCALE)

TITLE = 'THE ULTIMATE RECIPE INDEX!!!'
CREDITS = 'By Arwa, Ema, Mostafa, and Noon!!'

# Main Menu
MM1_TEXT_RECT_X_COORDINATES = int(500 * PROGRAM_SCALE)
MM1_TEXT_RECT_Y_COORDINATES = int(540 * PROGRAM_SCALE)
MM1_TEXT_RECT_X_DIMENSIONS = int(150 * PROGRAM_SCALE)
MM1_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
MM1_BUTTON_TEXT = "Survey"
MM1_BUTTON_TOP_LEFT_COORDINATES = (
    int(425 * PROGRAM_SCALE),
    int(590 * PROGRAM_SCALE)
)

MM2_TEXT_RECT_X_COORDINATES = int(500 * PROGRAM_SCALE)
MM2_TEXT_RECT_Y_COORDINATES = int(600 * PROGRAM_SCALE)
MM2_TEXT_RECT_X_DIMENSIONS = int(150 * PROGRAM_SCALE)
MM2_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
MM2_BUTTON_TEXT = "Search"
MM2_BUTTON_TOP_LEFT_COORDINATES = (
    int(425 * PROGRAM_SCALE),
    int(650 * PROGRAM_SCALE)
)

MM3_TEXT_RECT_X_COORDINATES = int(500 * PROGRAM_SCALE)
MM3_TEXT_RECT_Y_COORDINATES = int(660 * PROGRAM_SCALE)
MM3_TEXT_RECT_X_DIMENSIONS = int(150 * PROGRAM_SCALE)
MM3_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
MM3_BUTTON_TEXT = "Quit"
MM3_BUTTON_TOP_LEFT_COORDINATES = (
    int(425 * PROGRAM_SCALE),
    int(710 * PROGRAM_SCALE)
)

# Algorithm Screen
AS1_TEXT_RECT_X_COORDINATES = int(50 * PROGRAM_SCALE)
AS1_TEXT_RECT_Y_COORDINATES = int(50 * PROGRAM_SCALE)
AS1_TEXT_RECT_X_DIMENSIONS = int(160 * PROGRAM_SCALE)
AS1_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
AS1_BUTTON_TEXT = "Return to Menu"
AS1_BUTTON_TOP_LEFT_COORDINATES = (
    int(0 * PROGRAM_SCALE),
    int(0 * PROGRAM_SCALE)
)

AS2_TEXT_RECT_X_COORDINATES = int(100 * PROGRAM_SCALE)
AS2_TEXT_RECT_Y_COORDINATES = int(100 * PROGRAM_SCALE)
AS2_TEXT_RECT_X_DIMENSIONS = int(150 * PROGRAM_SCALE)
AS2_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
AS2_BUTTON_TEXT = "Submit"
AS2_BUTTON_TOP_LEFT_COORDINATES = (
    int(750 * PROGRAM_SCALE),
    int(700 * PROGRAM_SCALE)
)

AS3_TEXT_RECT_X_COORDINATES = int(100 * PROGRAM_SCALE)
AS3_TEXT_RECT_Y_COORDINATES = int(50 * PROGRAM_SCALE)
AS3_TEXT_RECT_X_DIMENSIONS = int(150 * PROGRAM_SCALE)
AS3_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
AS3_BUTTON_TEXT = "Next"
AS3_BUTTON_TOP_LEFT_COORDINATES = (
    int(800 * PROGRAM_SCALE),
    int(550 * PROGRAM_SCALE)
)

AS4_TEXT_RECT_X_COORDINATES = int(100 * PROGRAM_SCALE)
AS4_TEXT_RECT_Y_COORDINATES = int(50 * PROGRAM_SCALE)
AS4_TEXT_RECT_X_DIMENSIONS = int(150 * PROGRAM_SCALE)
AS4_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
AS4_BUTTON_TEXT = "Prev."
AS4_BUTTON_TOP_LEFT_COORDINATES = (
    int(700 * PROGRAM_SCALE),
    int(550 * PROGRAM_SCALE)
)

# Search Screen
SI1_TEXT_RECT_X_COORDINATES = int(50 * PROGRAM_SCALE)
SI1_TEXT_RECT_Y_COORDINATES = int(50 * PROGRAM_SCALE)
SI1_TEXT_RECT_X_DIMENSIONS = int(160 * PROGRAM_SCALE)
SI1_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
SI1_BUTTON_TEXT = "Return to Menu"
SI1_BUTTON_TOP_LEFT_COORDINATES = (
    int(0 * PROGRAM_SCALE),
    int(0 * PROGRAM_SCALE)
)

SI2_TEXT_RECT_X_COORDINATES = int(100 * PROGRAM_SCALE)
SI2_TEXT_RECT_Y_COORDINATES = int(100 * PROGRAM_SCALE)
SI2_TEXT_RECT_X_DIMENSIONS = int(150 * PROGRAM_SCALE)
SI2_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
SI2_BUTTON_TEXT = "Submit"
SI2_BUTTON_TOP_LEFT_COORDINATES = (
    int(700 * PROGRAM_SCALE),
    int(600 * PROGRAM_SCALE)
)

SI3_TEXT_RECT_X_COORDINATES = int(100 * PROGRAM_SCALE)
SI3_TEXT_RECT_Y_COORDINATES = int(50 * PROGRAM_SCALE)
SI3_TEXT_RECT_X_DIMENSIONS = int(150 * PROGRAM_SCALE)
SI3_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
SI3_BUTTON_TEXT = "Next"
SI3_BUTTON_TOP_LEFT_COORDINATES = (
    int(800 * PROGRAM_SCALE),
    int(550 * PROGRAM_SCALE)
)

SI4_TEXT_RECT_X_COORDINATES = int(100 * PROGRAM_SCALE)
SI4_TEXT_RECT_Y_COORDINATES = int(50 * PROGRAM_SCALE)
SI4_TEXT_RECT_X_DIMENSIONS = int(150 * PROGRAM_SCALE)
SI4_TEXT_RECT_Y_DIMENSIONS = int(45 * PROGRAM_SCALE)
SI4_BUTTON_TEXT = "Prev."
SI4_BUTTON_TOP_LEFT_COORDINATES = (
    int(700 * PROGRAM_SCALE),
    int(550 * PROGRAM_SCALE)
)

# Main Menu Text
MM_TEXT1_RECT_X = int(500 * PROGRAM_SCALE)
MM_TEXT1_RECT_Y = int(500 * PROGRAM_SCALE)
MM_TEXT1_RECT_W = int(1000 * PROGRAM_SCALE)
MM_TEXT1_RECT_H = int(1000 * PROGRAM_SCALE)
MM_TEXT1_TOP_LEFT = (
    int(175 * PROGRAM_SCALE),
    int(75 * PROGRAM_SCALE)
)

MM_TEXT2_RECT_X = int(500 * PROGRAM_SCALE)
MM_TEXT2_RECT_Y = int(500 * PROGRAM_SCALE)
MM_TEXT2_RECT_W = int(1000 * PROGRAM_SCALE)
MM_TEXT2_RECT_H = int(1000 * PROGRAM_SCALE)
MM_TEXT2_TOP_LEFT = (
    int(350 * PROGRAM_SCALE),
    int(150 * PROGRAM_SCALE)
)


# Algorithm Screen Text
AS_TEXT1_RECT_X = int(500 * PROGRAM_SCALE)
AS_TEXT1_RECT_Y = int(500 * PROGRAM_SCALE)
AS_TEXT1_RECT_W = int(1000 * PROGRAM_SCALE)
AS_TEXT1_RECT_H = int(60 * PROGRAM_SCALE)
AS_TEXT1_TOP_LEFT = (
    int(50 * PROGRAM_SCALE),
    int(50 * PROGRAM_SCALE)
)
AS_Q1_TEXT = '1. List Dietary Restrictions (Max 5). Enter 1 category at a time.'

AS_TEXT2_RECT_X = int(500 * PROGRAM_SCALE)
AS_TEXT2_RECT_Y = int(500 * PROGRAM_SCALE)
AS_TEXT2_RECT_W = int(1000 * PROGRAM_SCALE)
AS_TEXT2_RECT_H = int(60 * PROGRAM_SCALE)
AS_TEXT2_TOP_LEFT = (
    int(50 * PROGRAM_SCALE),
    int(170 * PROGRAM_SCALE)
)
AS_Q2_TEXT = '2. List ingredients you want to use (Max 5). Enter 1 ingredient at a time.'

AS_TEXT3_RECT_X = int(500 * PROGRAM_SCALE)
AS_TEXT3_RECT_Y = int(500 * PROGRAM_SCALE)
AS_TEXT3_RECT_W = int(1000 * PROGRAM_SCALE)
AS_TEXT3_RECT_H = int(60 * PROGRAM_SCALE)
AS_TEXT3_TOP_LEFT = (
    int(50 * PROGRAM_SCALE),
    int(290 * PROGRAM_SCALE)
)
AS_Q3_TEXT = '3. List any allergies (Max 5). Enter 1 ingredient to at a time.'

AS_TEXT4_RECT_X = int(500 * PROGRAM_SCALE)
AS_TEXT4_RECT_Y = int(500 * PROGRAM_SCALE)
AS_TEXT4_RECT_W = int(1000 * PROGRAM_SCALE)
AS_TEXT4_RECT_H = int(60 * PROGRAM_SCALE)
AS_TEXT4_TOP_LEFT = (
    int(50 * PROGRAM_SCALE),
    int(410 * PROGRAM_SCALE)
)
AS_Q4_TEXT = '(Optional) List one type of recipe you want to make.'

# Search Screen Text
SI_TEXT1_RECT_X = int(500 * PROGRAM_SCALE)
SI_TEXT1_RECT_Y = int(500 * PROGRAM_SCALE)
SI_TEXT1_RECT_W = int(450 * PROGRAM_SCALE)
SI_TEXT1_RECT_H = int(60 * PROGRAM_SCALE)
SI_TEXT1_TOP_LEFT = (
    int(200 * PROGRAM_SCALE),
    int(20 * PROGRAM_SCALE)
)
SI_FILTER1_TEXT = 'Filter by: Ingredients, Category'

SI_TEXT2_RECT_X = int(500 * PROGRAM_SCALE)
SI_TEXT2_RECT_Y = int(500 * PROGRAM_SCALE)
SI_TEXT2_RECT_W = int(450 * PROGRAM_SCALE)
SI_TEXT2_RECT_H = int(60 * PROGRAM_SCALE)
SI_TEXT2_TOP_LEFT = (
    int(600 * PROGRAM_SCALE),
    int(50 * PROGRAM_SCALE)
)
SI_FILTER2_TEXT = 'Search:'

SI_TEXT3_RECT_X = int(500 * PROGRAM_SCALE)
SI_TEXT3_RECT_Y = int(500 * PROGRAM_SCALE)
SI_TEXT3_RECT_W = int(450 * PROGRAM_SCALE)
SI_TEXT3_RECT_H = int(60 * PROGRAM_SCALE)
SI_TEXT3_TOP_LEFT = (
    int(50 * PROGRAM_SCALE),
    int(150 * PROGRAM_SCALE)
)
SI_FILTER3_TEXT = 'Results (max 50 recipes):'

# Algorithm Textboxes
AS_TB1_RECT_X = int(500 * PROGRAM_SCALE)
AS_TB1_RECT_Y = int(500 * PROGRAM_SCALE)
AS_TB1_RECT_W = int(450 * PROGRAM_SCALE)
AS_TB1_RECT_H = int(40 * PROGRAM_SCALE)
AS_TB1_TOP_LEFT = (int(50 * PROGRAM_SCALE), int(100 * PROGRAM_SCALE))

AS_TB2_RECT_X = int(500 * PROGRAM_SCALE)
AS_TB2_RECT_Y = int(500 * PROGRAM_SCALE)
AS_TB2_RECT_W = int(450 * PROGRAM_SCALE)
AS_TB2_RECT_H = int(40 * PROGRAM_SCALE)
AS_TB2_TOP_LEFT = (int(50 * PROGRAM_SCALE), int(220 * PROGRAM_SCALE))

AS_TB3_RECT_X = int(500 * PROGRAM_SCALE)
AS_TB3_RECT_Y = int(500 * PROGRAM_SCALE)
AS_TB3_RECT_W = int(450 * PROGRAM_SCALE)
AS_TB3_RECT_H = int(40 * PROGRAM_SCALE)
AS_TB3_TOP_LEFT = (int(50 * PROGRAM_SCALE), int(340 * PROGRAM_SCALE))

AS_TB4_RECT_X = int(500 * PROGRAM_SCALE)
AS_TB4_RECT_Y = int(500 * PROGRAM_SCALE)
AS_TB4_RECT_W = int(450 * PROGRAM_SCALE)
AS_TB4_RECT_H = int(40 * PROGRAM_SCALE)
AS_TB4_TOP_LEFT = (int(50 * PROGRAM_SCALE), int(460 * PROGRAM_SCALE))


# Search Textboxes
SI_TB1_RECT_X = int(500 * PROGRAM_SCALE)
SI_TB1_RECT_Y = int(500 * PROGRAM_SCALE)
SI_TB1_RECT_W = int(150 * PROGRAM_SCALE)
SI_TB1_RECT_H = int(40 * PROGRAM_SCALE)
SI_TB1_TOP_LEFT = (int(200 * PROGRAM_SCALE), int(50 * PROGRAM_SCALE))

SI_TB2_RECT_X = int(500 * PROGRAM_SCALE)
SI_TB2_RECT_Y = int(500 * PROGRAM_SCALE)
SI_TB2_RECT_W = int(150 * PROGRAM_SCALE)
SI_TB2_RECT_H = int(40 * PROGRAM_SCALE)
SI_TB2_TOP_LEFT = (int(400 * PROGRAM_SCALE), int(50 * PROGRAM_SCALE))

SI_TB3_RECT_X = int(500 * PROGRAM_SCALE)
SI_TB3_RECT_Y = int(500 * PROGRAM_SCALE)
SI_TB3_RECT_W = int(150 * PROGRAM_SCALE)
SI_TB3_RECT_H = int(40 * PROGRAM_SCALE)
SI_TB3_TOP_LEFT = (int(700 * PROGRAM_SCALE), int(50 * PROGRAM_SCALE))

# Algorithm Screen Textbox Limits
AS_TB1_LIMIT = 5
AS_TB2_LIMIT = 5
AS_TB3_LIMIT = 5
AS_TB4_LIMIT = 1

# Search Screen Textbox Limits
SI_TB1_LIMIT = 3
SI_TB2_LIMIT = 3
SI_TB3_LIMIT = 1

